// סקריפט להתקנת git pre-commit hook מקומי על העתק המקומי של המאגר.
//
// מריץ אוטומטית `dart format` ו-`dart analyze` על קבצי dart שנמצאים ב-staging
// לפני כל git commit, באמצעות חבילת dart_pre_commit.
//
// אופן השימוש:
//     dart run tool/install_git_hooks.dart
//
// יש להריץ פעם אחת לאחר clone של המאגר. ההוק אינו נשמר ב-git ולכן צריך
// להתקין אותו מחדש בכל מכונה.
//
// ניתן לעקוף את ההוק בעת קומיט יחיד עם `git commit --no-verify`, אבל זה
// אינו מומלץ - לפי הנחיות הפרויקט יש להריץ format ו-analyze לפני כל קומיט.

import 'dart:io';

Future<void> main() async {
  // שימוש ב-git עצמו כדי לכבד core.hooksPath, worktree ותצורות נוספות.
  final gitPathResult = await Process.run('git', [
    'rev-parse',
    '--git-path',
    'hooks/pre-commit',
  ]);
  if (gitPathResult.exitCode != 0) {
    stderr.writeln(
      'שגיאה: לא ניתן לאתר את נתיב ה-hook של git. הרץ את הסקריפט מתוך עץ עבודה תקין.',
    );
    exitCode = 1;
    return;
  }

  final hookPath = (gitPathResult.stdout as String).trim();
  if (hookPath.isEmpty) {
    stderr.writeln('שגיאה: git לא החזיר נתיב תקין ל-pre-commit hook.');
    exitCode = 1;
    return;
  }

  final preCommitHook = File(hookPath);
  await preCommitHook.parent.create(recursive: true);

  // הסקריפט שיורץ בכל git commit. אנו משתמשים ב-flutter כדי לוודא שה-SDK
  // הנכון של Flutter נטען (חשוב במכונות שבהן יש כמה גרסאות dart מותקנות).
  await preCommitHook.writeAsString(
    '''
#!/bin/sh
# Auto-generated by tool/install_git_hooks.dart - do not edit manually.
# Runs dart_pre_commit (format + analyze) on staged files.
exec flutter pub run dart_pre_commit
''',
  );

  if (!Platform.isWindows) {
    final result = await Process.run('chmod', ['a+x', preCommitHook.path]);
    if (result.exitCode != 0) {
      stderr.writeln('שגיאה בקביעת הרשאות הרצה: ${result.stderr}');
      exitCode = result.exitCode;
      return;
    }
  }

  stdout.writeln('git pre-commit hook הותקן בהצלחה ב-${preCommitHook.path}');
  stdout.writeln(
    'מעתה, dart format ו-dart analyze ירוצו אוטומטית לפני כל קומיט.',
  );
}
